CATEGORY_COLORS = {
    "Data Science": "#3b82f6",
    "ML/AI": "#8b5cf6",
    "Visualization": "#ec4899",
    "Utilities": "#10b981",
    "Finance": "#f59e0b",
    "Education": "#06b6d4",
}

APPS = [
    {
        "id": "python_mastery",
        "name": "Python Mastery",
        "category": "Education",
        "description": "Master Python fundamentals to advanced AI systems with PyTorch.",
        "detailed_description": "A complete learning path for Python, covering everything from basic syntax to advanced topics like decorators, generators, and deep learning with PyTorch.",
        "icon": "🐍",
        "tags": ["Python", "PyTorch", "Basics", "Advanced"],
        "difficulty": "Beginner",
        "launch_url": "https://python-mastery.streamlit.app/",
        "date_added": "2024-01-01",
        "last_updated": "2025-01-11",
        "featured": True,
        "popularity_score": 90,
        "tech_stack": ["python", "streamlit", "pytorch"],
    },
    {
        "id": "learn_ai",
        "name": "Learn AI & ML",
        "category": "ML/AI",
        "description": "From basics to production-ready AI systems and Neural Networks.",
        "detailed_description": "Deep dive into Artificial Intelligence and Machine Learning. Covers algorithms, neural networks, computer vision, and NLP.",
        "icon": "🧠",
        "tags": ["AI", "ML", "Deep Learning", "Neural Networks"],
        "difficulty": "Advanced",
        "launch_url": "https://learn-artificial-intelligence.streamlit.app/",
        "date_added": "2024-01-20",
        "last_updated": "2025-01-10",
        "featured": True,
        "popularity_score": 92,
        "tech_stack": ["tensorflow", "scikit-learn", "keras"],
    },
    {
        "id": "ai_hacks",
        "name": "AI Hacks (Nexus)",
        "category": "ML/AI",
        "description": "Central nexus for AI agents, tools, and workflows.",
        "detailed_description": "A comprehensive platform connecting various AI agents and tools. Explore next-gen AI capabilities and orchestrate complex workflows.",
        "icon": "🌌",
        "tags": ["Agents", "Orchestration", "LLMs"],
        "difficulty": "Advanced",
        "launch_url": "https://ai-hacks.streamlit.app/",
        "date_added": "2024-08-01",
        "last_updated": "2025-01-11",
        "featured": True,
        "popularity_score": 85,
        "tech_stack": ["langchain", "openai", "vectors"],
    },
    {
        "id": "automation_academy",
        "name": "Automation Academy",
        "category": "Education",
        "description": "Build robust test suites with Playwright and WebdriverIO.",
        "detailed_description": "Comprehensive guide to web automation using modern frameworks. Learn patterns, best practices, and CI/CD integration.",
        "icon": "🤖",
        "tags": ["Automation", "Playwright", "WebdriverIO"],
        "difficulty": "Intermediate",
        "launch_url": "https://automation-testing-academy.streamlit.app/",
        "date_added": "2024-03-01",
        "last_updated": "2025-01-11",
        "featured": True,
        "popularity_score": 88,
        "tech_stack": ["playwright", "webdriverio", "selenium"],
    },
    {
        "id": "perf_testing",
        "name": "Performance Testing",
        "category": "Education",
        "description": "Optimize systems with JMeter, k6, and Gatling at expert level.",
        "detailed_description": "Learn how to conduct performance testing using industry-standard tools like JMeter, k6, and Gatling. Understand throughput, latency, and scalability.",
        "icon": "⚡",
        "tags": ["Testing", "JMeter", "k6", "Gatling"],
        "difficulty": "Intermediate",
        "launch_url": "https://performance-testing.streamlit.app/",
        "date_added": "2024-02-15",
        "last_updated": "2025-01-10",
        "featured": False,
        "popularity_score": 85,
        "tech_stack": ["jmeter", "k6", "gatling"],
    },
    {
        "id": "coach_sushma",
        "name": "Coach Sushma",
        "category": "Education",
        "description": "Your personal AI coach for career growth and interview prep.",
        "detailed_description": "Interactive AI career coach. Get feedback on your resume, practice interviews, and receive personalized career advice.",
        "icon": "👩‍🏫",
        "tags": ["Career", "Interview", "Coaching", "Soft Skills"],
        "difficulty": "Beginner",
        "launch_url": "https://coach-sushma.streamlit.app",
        "date_added": "2024-06-01",
        "last_updated": "2025-01-11",
        "featured": True,
        "popularity_score": 89,
        "tech_stack": ["openai", "langchain", "prompt-engineering"],
    },
    {
        "id": "ai_finance",
        "name": "AI Finance",
        "category": "Finance",
        "description": "Smart market analysis and investment insights powered by AI.",
        "detailed_description": "Leverage AI for financial analysis. Predict trends, analyze sentiment, and optimize portfolios using machine learning models.",
        "icon": "💰",
        "tags": ["Finance", "Stocks", "Prediction", "Analysis"],
        "difficulty": "Advanced",
        "launch_url": "https://finance-india.streamlit.app/",
        "date_added": "2024-04-10",
        "last_updated": "2025-01-11",
        "featured": False,
        "popularity_score": 80,
        "tech_stack": ["yfinance", "pandas", "prophet"],
    },
    {
        "id": "ai_model_hunter",
        "name": "AI Model Hunter",
        "category": "Utilities",
        "description": "Discover and compare the best AI models for your use case.",
        "detailed_description": "A tool to search and compare various AI models based on metrics, size, and use cases. Find the perfect model for your project.",
        "icon": "🔍",
        "tags": ["Models", "HuggingFace", "Comparison"],
        "difficulty": "Intermediate",
        "launch_url": "https://ai-model-hunter.streamlit.app",
        "date_added": "2024-05-01",
        "last_updated": "2025-01-05",
        "featured": False,
        "popularity_score": 75,
        "tech_stack": ["huggingface", "api", "json"],
    },
    {
        "id": "website_ai_agent",
        "name": "Website AI Agent",
        "category": "Utilities",
        "description": "Intelligent agent for web scraping and content analysis.",
        "detailed_description": "An autonomous agent that can navigate websites, extract information, and summarize content based on your queries.",
        "icon": "🌐",
        "tags": ["Agent", "Scraping", "Analysis", "Automation"],
        "difficulty": "Advanced",
        "launch_url": "https://website-ai-agent.streamlit.app/",
        "date_added": "2024-07-01",
        "last_updated": "2025-01-10",
        "featured": False,
        "popularity_score": 78,
        "tech_stack": ["beautifulsoup", "selenium", "llm"],
    },
    {
        "id": "ppt_creator",
        "name": "PPT Creator",
        "category": "Utilities",
        "description": "Generate professional PowerPoint presentations instantly with AI.",
        "detailed_description": "Turn your topics or outlines into fully designed presentations. Customize themes, structures, and content automatically.",
        "icon": "📊",
        "tags": ["PPT", "GenAI", "Productivity"],
        "difficulty": "Beginner",
        "launch_url": "https://ppt-automation.streamlit.app/",
        "date_added": "2024-09-01",
        "last_updated": "2025-01-08",
        "featured": False,
        "popularity_score": 82,
        "tech_stack": ["python-pptx", "openai", "streamlit"],
    },
    {
        "id": "books_summary",
        "name": "Book Summarizer",
        "category": "Education",
        "description": "Get concise, actionable summaries from your favorite non-fiction books.",
        "detailed_description": "Analyze and summarize key takeaways from books. Save time and absorb knowledge faster with AI-generated insights.",
        "icon": "📚",
        "tags": ["Books", "Learning", "NLP"],
        "difficulty": "Beginner",
        "launch_url": "https://booksbrief.streamlit.app/",
        "date_added": "2024-08-15",
        "last_updated": "2025-01-09",
        "featured": False,
        "popularity_score": 70,
        "tech_stack": ["langchain", "openai", "nlp"],
    },

]
